日志页面请求时，接口报错 (vibe-kanban 736667b3)
错误信息如下：

\`\`\`
[2026-02-12 07:43:29] [INFO] [uvicorn.access] 172.27.0.1:53740 - "GET /api/admin/logs/stats?start\_time=2026-02-11T07:41:26.239Z&end\_time=2026-02-12T07:41:26.239Z&tz\_offset\_minutes=480&bucket=minute&bucket\_minutes=1&group\_by=request\_model HTTP/1.1" 500

[2026-02-12 07:43:29] [ERROR] [uvicorn.error] Exception in ASGI application

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 526, in \_prepare\_and\_execute

    prepared\_stmt, attributes = await adapt\_connection.\_prepare(

                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 773, in \_prepare

    prepared\_stmt = await self.\_connection.prepare(

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/asyncpg/connection.py", line 638, in prepare

    return await self.\_prepare(

           ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/asyncpg/connection.py", line 657, in \_prepare

    stmt = await self.\_get\_statement(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/asyncpg/connection.py", line 443, in \_get\_statement

    statement = await self.\_protocol.prepare(

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "asyncpg/protocol/protocol.pyx", line 165, in prepare

asyncpg.exceptions.UndefinedFunctionError: function make\_interval(integer, integer, integer, integer, integer, numeric, integer) does not exist

HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in \_exec\_single\_context

    self.dialect.do\_execute(

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 952, in do\_execute

    cursor.execute(statement, parameters)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 585, in execute

    self.\_adapt\_connection.await\_(

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/\_concurrency\_py3k.py", line 132, in await\_only

    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/\_concurrency\_py3k.py", line 196, in greenlet\_spawn

    value = await result

            ^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 563, in \_prepare\_and\_execute

    self.\_handle\_exception(error)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 513, in \_handle\_exception

    self.\_adapt\_connection.\_handle\_exception(error)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 797, in \_handle\_exception

    raise translated\_error from error

sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt\_asyncpg\_dbapi.ProgrammingError: <class 'asyncpg.exceptions.UndefinedFunctionError'>: function make\_interval(integer, integer, integer, integer, integer, numeric, integer) does not exist

HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools\_impl.py", line 416, in run\_asgi

    result = await app(  # type: ignore[func-returns-value]

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy\_headers.py", line 60, in **call**

    return await self.app(scope, receive, send)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1135, in **call**

    await super().**call**(scope, receive, send)

  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 107, in **call**

    await self.middleware\_stack(scope, receive, send)

  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in **call**

    raise exc

  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in **call**

    await self.app(scope, receive, \_send)

  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in **call**

    await self.app(scope, receive, send)

  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 63, in **call**

    await wrap\_app\_handling\_exceptions(self.app, conn)(scope, receive, send)

  File "/usr/local/lib/python3.12/site-packages/starlette/\_exception\_handler.py", line 53, in wrapped\_app

    raise exc

  File "/usr/local/lib/python3.12/site-packages/starlette/\_exception\_handler.py", line 42, in wrapped\_app

    await app(scope, receive, sender)

  File "/usr/local/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in **call**

    await self.app(scope, receive, send)

  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 716, in **call**

    await self.middleware\_stack(scope, receive, send)

  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 736, in app

    await route.handle(scope, receive, send)

  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 290, in handle

    await self.app(scope, receive, send)

  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 115, in app

    await wrap\_app\_handling\_exceptions(app, request)(scope, receive, send)

  File "/usr/local/lib/python3.12/site-packages/starlette/\_exception\_handler.py", line 53, in wrapped\_app

    raise exc

  File "/usr/local/lib/python3.12/site-packages/starlette/\_exception\_handler.py", line 42, in wrapped\_app

    await app(scope, receive, sender)

  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 101, in app

    response = await f(request)

               ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 355, in app

    raw\_response = await run\_endpoint\_function(

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 243, in run\_endpoint\_function

    return await dependant.call(\*\*values)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/backend/app/api/admin/logs.py", line 105, in get\_log\_cost\_stats

    return await service.get\_cost\_stats(query)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/backend/app/services/log\_service.py", line 138, in get\_cost\_stats

    return await self.repo.get\_cost\_stats(query)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/backend/app/repositories/sqlalchemy/log\_repo.py", line 393, in get\_cost\_stats

    trend\_rows = (await self.session.execute(trend\_stmt)).mappings().all()

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/session.py", line 449, in execute

    result = await greenlet\_spawn(

             ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/\_concurrency\_py3k.py", line 201, in greenlet\_spawn

    result = context.throw(\*sys.exc\_info())

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2351, in execute

    return self.\_execute\_internal(

           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2249, in \_execute\_internal

    result: Result[Any] = compile\_state\_cls.orm\_execute\_statement(

                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 306, in orm\_execute\_statement

    result = conn.execute(

             ^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1419, in execute

    return meth(

           ^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 527, in \_execute\_on\_connection

    return connection.\_execute\_clauseelement(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1641, in \_execute\_clauseelement

    ret = self.\_execute\_context(

          ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in \_execute\_context

    return self.\_exec\_single\_context(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in \_exec\_single\_context

    self.\_handle\_dbapi\_exception(

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2363, in \_handle\_dbapi\_exception

    raise sqlalchemy\_exception.with\_traceback(exc\_info[2]) from e

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in \_exec\_single\_context

    self.dialect.do\_execute(

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 952, in do\_execute

    cursor.execute(statement, parameters)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 585, in execute

    self.\_adapt\_connection.await\_(

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/\_concurrency\_py3k.py", line 132, in await\_only

    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/\_concurrency\_py3k.py", line 196, in greenlet\_spawn

    value = await result

            ^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 563, in \_prepare\_and\_execute

    self.\_handle\_exception(error)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 513, in \_handle\_exception

    self.\_adapt\_connection.\_handle\_exception(error)

  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 797, in \_handle\_exception

    raise translated\_error from error

sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedFunctionError'>: function make\_interval(integer, integer, integer, integer, integer, numeric, integer) does not exist

HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT (date\_trunc($1::VARCHAR, request\_logs.request\_time + make\_interval($2::INTEGER, $3::INTEGER, $4::INTEGER, $5::INTEGER, $6::INTEGER, $7::INTEGER, $8::INTEGER)) + make\_interval($9::INTEGER, $10::INTEGER, $11::INTEGER, $12::INTEGER, $13::INTEGER, floor(EXTRACT(minute FROM request\_logs.request\_time + make\_interval($2::INTEGER, $3::INTEGER, $4::INTEGER, $5::INTEGER, $6::INTEGER, $7::INTEGER, $8::INTEGER)) / CAST($14::INTEGER AS NUMERIC)) *&#32;$15::INTEGER, $16::INTEGER)) - make\_interval($17::INTEGER, $18::INTEGER, $19::INTEGER, $20::INTEGER, $21::INTEGER, $22::INTEGER, $23::INTEGER) AS bucket, count(*) AS request\_count, coalesce(sum(request\_logs.total\_cost), $24::INTEGER) AS total\_cost, coalesce(sum(request\_logs.input\_cost), $25::INTEGER) AS input\_cost, coalesce(sum(request\_logs.output\_cost), $26::INTEGER) AS output\_cost, coalesce(sum(request\_logs.input\_tokens), $27::INTEGER) AS input\_tokens, coalesce(sum(request\_logs.output\_tokens), $28::INTEGER) AS output\_tokens, coalesce(sum(CASE WHEN (request\_logs.error\_info IS NOT NULL OR request\_logs.response\_status >= $29::INTEGER) THEN $30::INTEGER ELSE $31::INTEGER END), $32::INTEGER) AS error\_count

FROM request\_logs

WHERE request\_logs.request\_time >= $33::TIMESTAMP WITHOUT TIME ZONE AND request\_logs.request\_time <= $34::TIMESTAMP WITHOUT TIME ZONE GROUP BY (date\_trunc($1::VARCHAR, request\_logs.request\_time + make\_interval($2::INTEGER, $3::INTEGER, $4::INTEGER, $5::INTEGER, $6::INTEGER, $7::INTEGER, $8::INTEGER)) + make\_interval($9::INTEGER, $10::INTEGER, $11::INTEGER, $12::INTEGER, $13::INTEGER, floor(EXTRACT(minute FROM request\_logs.request\_time + make\_interval($2::INTEGER, $3::INTEGER, $4::INTEGER, $5::INTEGER, $6::INTEGER, $7::INTEGER, $8::INTEGER)) / CAST($14::INTEGER AS NUMERIC)) \* $15::INTEGER, $16::INTEGER)) - make\_interval($17::INTEGER, $18::INTEGER, $19::INTEGER, $20::INTEGER, $21::INTEGER, $22::INTEGER, $23::INTEGER) ORDER BY (date\_trunc($1::VARCHAR, request\_logs.request\_time + make\_interval($2::INTEGER, $3::INTEGER, $4::INTEGER, $5::INTEGER, $6::INTEGER, $7::INTEGER, $8::INTEGER)) + make\_interval($9::INTEGER, $10::INTEGER, $11::INTEGER, $12::INTEGER, $13::INTEGER, floor(EXTRACT(minute FROM request\_logs.request\_time + make\_interval($2::INTEGER, $3::INTEGER, $4::INTEGER, $5::INTEGER, $6::INTEGER, $7::INTEGER, $8::INTEGER)) / CAST($14::INTEGER AS NUMERIC)) \* $15::INTEGER, $16::INTEGER)) - make\_interval($17::INTEGER, $18::INTEGER, $19::INTEGER, $20::INTEGER, $21::INTEGER, $22::INTEGER, $23::INTEGER)]

[parameters: ('hour', 0, 0, 0, 0, 0, 480, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 480, 0, 0, 0, 0, 0, 0, 400, 1, 0, 0, datetime.datetime(2026, 2, 11, 7, 41, 26, 239000), datetime.datetime(2026, 2, 12, 7, 41, 26, 239000))]

(Background on this error at: https://sqlalche.me/e/20/f405)
\`\`\`